import json
json_data ='''
{
    "cities_and_stations": {
      "New Delhi": ["New Delhi Railway Station" ],
      "Mumbai": ["Mumbai Central Railway Station"],
      "Kolkata": ["Howrah Junction", "Sealdah"],
      "Chennai": ["Chennai Central"],
      "Bangalore": ["Krishnarajapuram"],
      "Ahmedabad": ["Ahmedabad Junction"],
      "Pune": ["Pune Junction"],
      "Lucknow": ["Lucknow Charbagh"],
      "Patna": ["Patna Junction"],
      "Varanasi": ["Varanasi Junction"],
      "Nagpur": ["Nagpur Junction"],
      "Thane": ["Thane Railway Station"],
      "Visakhapatnam": ["Visakhapatnam Railway Station"],
      "Agra": ["Agra Cantt"],
      "Vijayawada": ["Vijayawada Junction"],
      "Amritsar": ["Amritsar Junction"],
      "Kochi": ["Ernakulam Junction"],
      "Ghaziabad": ["Ghaziabad Railway Station"],
      "Madurai": ["Madurai Junction"],
      "Raipur": ["Raipur Junction"],
      "Allahabad": ["Allahabad Junction"],
      "Ranchi": ["Ranchi Junction"],
      "Trivandrum": ["Thiruvananthapuram Central"],
      "Srinagar": ["Srinagar Railway Station"],
      "Kozhikode": ["Kozhikode Railway Station"],
      "Udaipur": ["Udaipur City Railway Station"],
      "Cuttack": ["Cuttack Railway Station"],
      "Siliguri": ["New Jalpaiguri Railway Station"],
      "Salem": ["Salem Junction"],
      "Vadodara": ["Vadodara Junction"],
      "Moradabad": ["Moradabad Railway Station"],
      "Shimla": ["Kalka Shimla Railway"],
      "Mysore": ["Mysore Junction"],
      "Kanyakumari": ["Kanyakumari Railway Station"],
      "Ajmer": ["Ajmer Junction"],
      "Tiruchirappalli": ["Tiruchirappalli Junction"],
      "Rajkot": ["Rajkot Junction"],
      "Tirupati": ["Tirupati Main"],
      "Firozabad": ["Firozabad Railway Station"],
      "Nellore": ["Nellore Railway Station"],
      "Eluru": ["Eluru Railway Station"],
      "Panipat": ["Panipat Junction"],
      "Rohtak": ["Rohtak Junction"],
      "Kurnool": ["Kurnool City"],
      "Tirupur": ["Tiruppur Railway Station"],
      "Darbhanga": ["Darbhanga Junction"],
      "Sangli": ["Sangli Railway Station"],
      "Bardhaman": ["Bardhaman Junction"],
      "Bharatpur": ["Bharatpur Junction"],
      "Shahjahanpur": ["Shahjahanpur Railway Station"],
      "Satna": ["Satna Railway Station"],
      "Bally": ["Bally Railway Station"],
      "Khammam": ["Khammam Railway Station"],
      "Patiala": ["Patiala Railway Station"],
      "Muzaffarnagar": ["Muzaffarnagar Railway Station"],
      "Shivpuri": ["Shivpuri Railway Station"],
      "Unnao": ["Unnao Railway Station"],
      "Porbandar": ["Porbandar Railway Station"],
      "Jind": ["Jind Junction"],
      "Rourkela": ["Rourkela Railway Station"],
      "Nanded": ["Nanded Railway Station"],
      "Mirzapur": ["Mirzapur Railway Station"],
      "Morena": ["Morena Railway Station"],
      "Sambalpur": ["Sambalpur Railway Station"],
      "Surendranagar": ["Surendranagar Railway Station"],
      "Ratnagiri": ["Ratnagiri Railway Station"],
      "Barasat": ["Barasat Junction"],
      "Palakkad": ["Palakkad Junction"],
      "Hajipur": ["Hajipur Junction"],
      "Etah": ["Etah Railway Station"],
      "Nizamabad": ["Nizamabad Railway Station"],
      "Faridkot": ["Faridkot Railway Station"],
      "Machilipatnam": ["Machilipatnam Railway Station"],
      "Silchar": ["Silchar Railway Station"],
      "Valsad": ["Valsad Railway Station"],
      "Rewa": ["Rewa Railway Station"],
      "Palanpur": ["Palanpur Junction"],
      "Rae Bareli": ["Rae Bareli Junction"],
      "Hosur": ["Hosur Railway Station"],
      "Ambala": ["Ambala Cantonment"],
      "Pathankot": ["Pathankot Railway Station"],
      "Rajahmundry": ["Rajahmundry Railway Station"],
      "Shimoga": ["Shimoga Town Railway Station"],
      "Balangir": ["Balangir Railway Station"],
      "Sonipat": ["Sonipat Railway Station"],
      "Karur": ["Karur Railway Station"],
      "Rampur": ["Rampur Railway Station"],
      "Palwal": ["Palwal Railway Station"],
      "Baraut": ["Baraut Railway Station"],
      "Madhubani": ["Madhubani Railway Station"],
      "Tiruvannamalai": ["Tiruvannamalai Railway Station"],
      "Ballia": ["Ballia Railway Station"],
      "Sitapur": ["Sitapur Cantt. Railway Station"],
      "Bharuch": ["Bharuch Junction"],
      "Tenali": ["Tenali Junction"],
      "Nabadwip": ["Nabadwip Dham Railway Station"],
      "Shahabad": ["Shahabad Markanda Railway Station"],
      "Saharsa": ["Saharsa Junction"],
      "Mahesana": ["Mahesana Junction"],
      "Rajpura": ["Rajpura Junction"],
      "Kannur": ["Kannur Railway Station"],
      "Katihar": ["Katihar Junction"],
      "Bongaon": ["Bongaon Railway Station"],
      "Baran": ["Baran Railway Station"],
      "Tamluk": ["Tamluk Railway Station"],
      "Dehri": ["Dehri On Sone Railway Station"],
      "Baripada": ["Baripada Railway Station"],
      "Kasganj": ["Kasganj Railway Station"],
      "Vrindavan": ["Vrindavan Railway Station"],
      "Bahraich": ["Bahraich Railway Station"],
      "Junagadh": ["Junagadh Junction"],
      "Navsari": ["Navsari Railway Station"],
      "Narnaul": ["Narnaul Railway Station"],
      "Beawar": ["Beawar Railway Station"],
      "Sehore": ["Sehore Railway Station"],
      "Chandauli": ["Chandauli Railway Station"],
      "Sambhal": ["Sambhal Railway Station"],
      "Koderma": ["Koderma Railway Station"],
      "Miryalaguda": ["Miryalaguda Railway Station"],
      "Medinipur": ["Medinipur Railway Station"],
      "Ujjain": ["Ujjain Junction"],
      "Angul": ["Angul Railway Station"],
      "Navapur": ["Navapur Railway Station"],
      "Sawai Madhopur": ["Sawai Madhopur Railway Station"],
      "Arakkonam": ["Arakkonam Junction"],
      "Sivakasi": ["Sivakasi Railway Station"],
      "Barmer": ["Barmer Railway Station"],
      "Sagar": ["Sagar Railway Station"],
      "Tirunelveli": ["Tirunelveli Railway Station"],
      "Ballabhgarh": ["Ballabhgarh Railway Station"],
      "Sultanpur": ["Sultanpur Railway Station"],
      "Kollam": ["Kollam Junction"],
      "Chalisgaon": ["Chalisgaon Junction"],
      "Virar": ["Virar Railway Station"],
      "Siddipet": ["Siddipet Railway Station"],
      "Rajgir": ["Rajgir Railway Station"],
      "Kota": ["Kota Junction"],
      "Pilibhit": ["Pilibhit Junction"],
      "Nalgonda": ["Nalgonda Railway Station"],
      "Buxar": ["Buxar Railway Station"],
      "Siwan": ["Siwan Junction"],
      "Godhra": ["Godhra Junction"],
      "Sirsa": ["Sirsa Railway Station"],
      "Mandla": ["Mandla Fort Railway Station"],
      "Khambhat": ["Khambhat Railway Station"],
      "Phagwara": ["Phagwara Junction"],
      "Korba": ["Korba Railway Station"],
      "Sindhudurg": ["Sindhudurg Railway Station"],
      "Rishikesh": ["Rishikesh Railway Station"],
      "Nawanshahr": ["Nawanshahr Railway Station"],
      "Baghpat": ["Baghpat Road Railway Station"],
      "Malappuram": ["Angadipuram Railway Station"],
      "Kottayam": ["Kottayam Railway Station"],
      "Mandi": ["Mandi Railway Station"],
      "Panvel": ["Panvel Railway Station"],
      "Roorkee": ["Roorkee Railway Station"],
      "Sonbhadra": ["Chopan Railway Station"],
      "Ghatshila": ["Ghatshila Railway Station"],
      "Pudukkottai": ["Pudukkottai Railway Station"],
      "Medininagar": ["Daltonganj Railway Station"],
      "Jajpur": ["Jajpur Keonjhar Road"],
      "Narasaraopet": ["Narasaraopet Railway Station"],
      "Mettupalayam": ["Mettupalayam Railway Station"],
      "Shamli": ["Shamli Railway Station"],
      "Ramanathapuram": ["Ramanathapuram Railway Station"],
      "Dumka": ["Dumka Railway Station"],
      "Bulandshahr": ["Bulandshahr Railway Station"],
      "Sikar": ["Sikar Junction"],
      "Bathinda": ["Bathinda Junction"],
      "Dhamtari": ["Dhamtari Railway Station"],
      "Adilabad": ["Adilabad Railway Station"],
      "Adoni": ["Adoni Railway Station"],
      "Abohar": ["Abohar Railway Station"],
      "Achalpur": ["Achalpur Railway Station"],
      "Agartala": ["Agartala Railway Station"],
      "Akola": ["Akola Junction"],
      "Alappuzha": ["Alappuzha Railway Station"],
      "Aligarh": ["Aligarh Junction"],
      "Alipurduar": ["Alipurduar Junction"],
      "Amalner": ["Amalner Railway Station"],
      "Amalapuram": ["Amalapuram Railway Station"],
      "Ambikapur": ["Ambikapur Railway Station"],
      "Amravati": ["Amravati Railway Station"],
      "Anand": ["Anand Junction"],
      "Anandapur": ["Anandapur Railway Station"],
      "Anantapur": ["Anantapur Railway Station"],
      "Anara": ["Anara Railway Station"],
      "Ankleshwar": ["Ankleshwar Junction"],
      "Asansol": ["Asansol Junction"],
      "Aurangabad": ["Aurangabad Railway Station"],
      "Ayodhya": ["Ayodhya Railway Station"],
      "Azamgarh": ["Azamgarh Railway Station"],
      "Badaun": ["Badaun Railway Station"],
      "Baddi": ["Baddi Railway Station"],
      "Bakhtiyarpur": ["Bakhtiyarpur Railway Station"],
      "Balaghat": ["Balaghat Junction"],
      "Balasore": ["Balasore Railway Station"],
      "Balrampur": ["Balrampur Railway Station"],
      "Balugaon": ["Balugaon Railway Station"],
      "Bankura": ["Bankura Railway Station"],
      "Banswara": ["Banswara Railway Station"],
      "Barabanki": ["Barabanki Junction"],
      "Barbil": ["Barbil Railway Station"],
      "Barddhaman": ["Barddhaman Junction"],
      "Bardoli": ["Bardoli Railway Station"],
      "Bareilly": ["Bareilly Junction"],
      "Barh": ["Barh Railway Station"],
      "Barhiya": ["Barhiya Railway Station"],
      "Bari": ["Bari Railway Station"],
      "Barka": ["Barka Railway Station"],
      "Barnala": ["Barnala Railway Station"],
      "Barpeta Road": ["Barpeta Road Railway Station"],
      "Baruipur": ["Baruipur Junction"],
      "Basti": ["Basti Railway Station"],
      "Basudebpur": ["Basudebpur Railway Station"],
      "Beas": ["Beas Railway Station"],
      "Begusarai": ["Begusarai Railway Station"],
      "Behala": ["Behala Chowrasta"],
      "Belagavi": ["Belagavi Railway Station"],
      "Belapur": ["Belapur Railway Station"],
      "Belda": ["Belda Railway Station"],
      "Beldubi": ["Beldubi Railway Station"],
      "Beldanga": ["Beldanga Railway Station"],
      "Belgaum": ["Belgaum Railway Station"],
      "Bellampalli": ["Bellampalli Railway Station"],
      "Belpahar": ["Belpahar Railway Station"],
      "Belthara Road": ["Belthara Road Railway Station"],
      "Belur": ["Belur Railway Station"],
      "Benaras": ["Benaras Railway Station"],
      "Bengaluru": ["Bengaluru City Junction"],
      "Berhampur": ["Berhampur Railway Station"],
      "Bhadohi": ["Bhadohi Railway Station"],
      "Bhadrachalam": ["Bhadrachalam Road"],
      "Bhadreswar": ["Bhadreswar Railway Station"],
      "Bhagalpur": ["Bhagalpur Junction"],
      "Bhainsa": ["Bhainsa Railway Station"],
      "Bhayandar": ["Bhayandar Railway Station"],
      "Bhavnagar": ["Bhavnagar Terminus"],
      "Bhavnagar Para": ["Bhavnagar Para Railway Station"],
      "Bhilai": ["Bhilai Power House Railway Station"],
      "Bhilwara": ["Bhilwara Railway Station"],
      "Bhimavaram": ["Bhimavaram Junction"],
      "Bhind": ["Bhind Railway Station"],
      "Bhinga": ["Bhinga Railway Station"],
      "Bhongir": ["Bhongir Railway Station"],
      "Bhopal": ["Bhopal Junction"],
      "Bhubaneswar": ["Bhubaneswar Railway Station"],
      "Bhuj": ["Bhuj Railway Station"],
      "Bhusawal": ["Bhusawal Junction"],
      "Bidar": ["Bidar Railway Station"],
      "Bihar Sharif": ["Bihar Sharif Railway Station"],
      "Bijapur": ["Bijapur Railway Station"],
      "Bikaner": ["Bikaner Junction"],
      "Bilaspur": ["Bilaspur Junction"],
      "Bilaspur Road": ["Bilaspur Road Railway Station"],
      "Bina": ["Bina Junction"],
      "Birur": ["Birur Junction"],
      "Bokaro": ["Bokaro Steel City"],
      "Bongaigaon": ["Bongaigaon Railway Station"],
      "Brahmapur": ["Brahmapur Railway Station"],
      "Budaun": ["Budaun Railway Station"],
      "Budge Budge": ["Budge Budge Railway Station"],
      "Bundi": ["Bundi Railway Station"],
      "Burnpur": ["Burnpur Railway Station"],
      "Calicut": ["Calicut Railway Station"],
      "Chandigarh": ["Chandigarh Junction"],
      "Chandil": ["Chandil Junction"],
      "Chandrapur": ["Chandrapur Railway Station"],
      "Chapra": ["Chapra Railway Station"],
      "Chengalpattu": ["Chengalpattu Railway Station"],
      "Chhapra": ["Chhapra Junction"],
      "Chhindwara": ["Chhindwara Junction"],
      "Chikmagalur": ["Chikmagalur Railway Station"],
      "Chiplun": ["Chiplun Railway Station"],
      "Chitradurga": ["Chitradurga Railway Station"],
      "Chittaranjan": ["Chittaranjan Railway Station"],
      "Chitrakutdham": ["Chitrakutdham Karwi Railway Station"],
      "Chittorgarh": ["Chittorgarh Railway Station"],
      "Chittoor": ["Chittoor Railway Station"],
      "Chittapur": ["Chittapur Railway Station"],
      "Churu": ["Churu Railway Station"],
      "Coimbatore": ["Coimbatore Junction"],
      "Cooch Behar": ["Cooch Behar Railway Station"],
      "Dadri": ["Dadri Railway Station"],
      "Daltonganj": ["Daltonganj Railway Station"],
      "Daman": ["Daman Railway Station"],
      "Dankuni": ["Dankuni Railway Station"],
      "Dausa": ["Dausa Railway Station"],
      "Dehradun": ["Dehradun Railway Station"],
      "Deoghar": ["Deoghar Railway Station"],
      "Deori": ["Deori Railway Station"],
      "Dewas": ["Dewas Junction"],
      "Dhanbad": ["Dhanbad Junction"],
      "Dhar": ["Dhar Railway Station"],
      "Dharmapuri": ["Dharmapuri Railway Station"],
      "Dharmavaram": ["Dharmavaram Junction"],
      "Dharwad": ["Dharwad Railway Station"],
      "Dholpur": ["Dholpur Junction"],
      "Dhule": ["Dhule Railway Station"],
      "Dibrugarh": ["Dibrugarh Railway Station"],
      "Dimapur": ["Dimapur Railway Station"],
      "Dindigul": ["Dindigul Junction"],
      "Durg": ["Durg Junction"],
      "Durgapur": ["Durgapur Railway Station"],
      "Edapally": ["Edapally Railway Station"],
      "Erode": ["Erode Junction"],
      "Etawah": ["Etawah Junction"],
      "Faizabad": ["Faizabad Junction"],
      "Falna": ["Falna Railway Station"],
      "Farrukhabad": ["Farrukhabad Railway Station"],
      "Fatehabad": ["Fatehabad Railway Station"],
      "Fatehpur": ["Fatehpur Railway Station"],
      "Fatehpur Sikri": ["Fatehpur Sikri Railway Station"],
      "Fazilka": ["Fazilka Railway Station"],
      "Firozpur": ["Firozpur Cantonment Railway Station"],
      "Firozpur City": ["Firozpur City Railway Station"],
      "Fursatganj": ["Fursatganj Railway Station"],
      "Gadag": ["Gadag Junction"],
      "Gadarpur": ["Gadarpur Railway Station"],
      "Gadarwara": ["Gadarwara Railway Station"],
      "Gandhidham": ["Gandhidham Junction"],
      "Gandhinagar": ["Gandhinagar Railway Station"],
      "Gangapur": ["Gangapur Railway Station"],
      "Gangtok": ["Gangtok Railway Station"],
      "Gangwal Bus Stand": ["Gangwal Bus Stand Railway Station"],
      "Gariaband": ["Gariaband Railway Station"],
      "Garwa Road": ["Garwa Road Railway Station"],
      "Gauriganj": ["Gauriganj Railway Station"],
      "Gaya": ["Gaya Junction"],
      "Ghaghara": ["Ghaghara Railway Station"],
      "Ghazipur": ["Ghazipur City Railway Station"],
      "Giridih": ["Giridih Railway Station"],
      "Gobichettipalayam": ["Gobichettipalayam Railway Station"],
      "Gogamukh": ["Gogamukh Railway Station"],
      "Gohad": ["Gohad Road Railway Station"],
      "Gokarna": ["Gokarna Road Railway Station"],
      "Gokavaram": ["Gokavaram Railway Station"],
      "Gola Gokaran Nath": ["Gola Gokaran Nath Railway Station"],          
      "Gonda": ["Gonda Junction"],
      "Gondal": ["Gondal Railway Station"],
      "Gondia": ["Gondia Junction"],
      "Gooty": ["Gooty Railway Station"],
      "Gorakhpur": ["Gorakhpur Junction"],
      "Gosainganj": ["Gosainganj Railway Station"],
      "Govindgarh": ["Govindgarh Railway Station"],
      "Gudur": ["Gudur Junction"],
      "Gulbarga": ["Gulbarga Railway Station"],
      "Gulzarbagh": ["Gulzarbagh Railway Station"],
      "Guna": ["Guna Junction"],
      "Guntakal": ["Guntakal Junction"],
      "Guntur": ["Guntur Junction"],
      "Gurdaspur": ["Gurdaspur Railway Station"],
      "Gurgaon": ["Gurgaon Railway Station"],
      "Guwahati": ["Guwahati Railway Station"],
      "Gwalior": ["Gwalior Junction"],
      "Habra": ["Habra Railway Station"],
      "Haldia": ["Haldia Railway Station"],
      "Haldibari": ["Haldibari Railway Station"],
      "Halisahar": ["Halisahar Railway Station"],
      "Hansi": ["Hansi Railway Station"],
      "Hanumangarh": ["Hanumangarh Junction"],
      "Hapur": ["Hapur Railway Station"],
      "Hardoi": ["Hardoi Railway Station"],
      "Harihar": ["Harihar Railway Station"],
      "Haridwar": ["Haridwar Junction"],
      "Hathras": ["Hathras Railway Station"],
      "Hazaribagh": ["Hazaribagh Road Railway Station"],
      "Himatnagar": ["Himatnagar Railway Station"],
      "Hindaun": ["Hindaun City Railway Station"],
      "Hisar": ["Hisar Railway Station"],
      "Hoshangabad": ["Hoshangabad Railway Station"],
      "Hoshiarpur": ["Hoshiarpur Railway Station"],
      "Howrah": ["Howrah Junction"],
      "Hubli": ["Hubli Junction"],
      "Hyderabad": ["Hyderabad Deccan Nampally"],
      "Igatpuri": ["Igatpuri Railway Station"],
      "Imphal": ["Imphal Railway Station"],
      "Indore": ["Indore Junction"],
      "Itarsi": ["Itarsi Junction"],
      "Jabalpur": ["Jabalpur Junction"],
      "Jadcherla": ["Jadcherla Railway Station"],
      "Jaipur": ["Jaipur Junction"],
      "Jaisalmer": ["Jaisalmer Railway Station"],
      "Jalandhar": ["Jalandhar City Railway Station"],
      "Jalgaon": ["Jalgaon Junction"],
      "Jalna": ["Jalna Railway Station"],
      "Jalore": ["Jalore Railway Station"],
      "Jalpaiguri": ["Jalpaiguri Railway Station"],
      "Jamalpur": ["Jamalpur Junction"],
      "Jammu": ["Jammu Tawi"],
      "Jamnagar": ["Jamnagar Railway Station"],
      "Jamshedpur": ["Tatanagar Junction"],
      "Jamui": ["Jamui Railway Station"],
      "Janjgir": ["Janjgir Naila Railway Station"],
      "Jasidih": ["Jasidih Junction"],
      "Jaunpur": ["Jaunpur Junction"],
      "Jehanabad": ["Jehanabad Railway Station"],
      "Jeypore": ["Jeypore Railway Station"],
      "Jhabua": ["Jhabua Road Railway Station"],
      "Jhajha": ["Jhajha Railway Station"],
      "Jhalawar": ["Jhalawar City Railway Station"],
      "Jhansi": ["Jhansi Junction"],
      "Jhargram": ["Jhargram Railway Station"],
      "Jharsuguda": ["Jharsuguda Junction"],
      "Jhinjhak": ["Jhinjhak Railway Station"],
      "Jhunjhunu": ["Jhunjhunu Railway Station"],
      "Jodhpur": ["Jodhpur Junction"],
      "Jorhat": ["Jorhat Town Railway Station"],
      "Junnar": ["Junnar Railway Station"],
      "Kadapa": ["Kadapa Railway Station"],
      "Kakinada": ["Kakinada Town Railway Station"],
      "Kalaburagi": ["Kalaburagi Railway Station"],
      "Kalahandi": ["Kalahandi Railway Station"],
      "Kalamnuri": ["Kalamnuri Railway Station"],
      "Kalburgi": ["Kalburgi Railway Station"],
      "Kalka": ["Kalka Railway Station"],
      "Kalyan": ["Kalyan Junction"],
      "Kalyani": ["Kalyani Railway Station"],
      "Kamakhya": ["Kamakhya Junction"],
      "Kamareddy": ["Kamareddy Railway Station"],
      "Kanchipuram": ["Kanchipuram Railway Station"],
      "Kandla": ["Kandla Port Railway Station"],
      "Kannauj": ["Kannauj Railway Station"],
      "Kanniyakumari": ["Kanniyakumari Railway Station"],
      "Kanpur": ["Kanpur Central"],
      "Kapurthala": ["Kapurthala Railway Station"],
      "Karaikal": ["Karaikal Railway Station"],
      "Karauli": ["Karauli Railway Station"],
      "Karimnagar": ["Karimnagar Railway Station"]
    }
  }'''
data = json.loads(json_data)
i=0

for city, stations in data['cities_and_stations'].items():
    for city2, stations2 in data['cities_and_stations'].items():
        if city2 == city:
            break
        i=i+1
print(i)

# print(city2 + ":", stations2[0])



          
      
